version: '3.7'

services:
  poc-gql-apirestful:
    build: .
    image: api-mongo:poc
    container_name: poc-gql-apirestful
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - "./app:/app/app"
      - "./data:/app/data"
    networks:
      - poc-graphql

networks:
  poc-graphql:
    name: poc-graphql
    external: true
